### DISCUSSION TITLE
Query regarding deploying infrastructure directly using bicep files under infra

### DISCUSSION THREAD

**Discussion by vaiddas** [microsoft/sample-app-aoai-chatGPT#919] [General]
I am trying to deploy the infrastructure  using GitHub action and passing parameters in separate json file. 

```
    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      id: deploy
      with:
          subscriptionId: "xxxxx"
          scope: subscription
          region: 'xxxxx'
          template: infra/main.bicep
          parameters: infra/parameters.json
          deploymentName: xxxxxxx
```

I have a query:

1. Can I deploy resources using directly main.bicep and passing parameters? 
2. I am using Service Principal to deploy the resources but I can see that some roles in main.bicep such as "openAiRoleUser" or "searchRoleUser" or "searchIndexDataContribRoleUser" have principalType: 'User'

 I am using SP to deploy the resources so I have set principal ID of SP in my parameters. 
But I get an error something like:

```
"message"
: 
"The PrincipalId 'xxxxxxx' has type 'ServicePrincipal' , which is different from specified PrinciaplType 'User'."
```
so either I need to change the main.bicep to have `principalType: 'ServicePrincipal'` or use "some user's principal ID" to deploy all resources. 

I wanted to understand if I am not supposed to use SP to deploy the resources ? 
if I can use both user id as well as Service Principal then why I am getting this error? 
what would be the impact if I change the `principalType: 'ServicePrincipal'` and then deploy the roles? I tried and everything got deployed but I am not sure if that's the correct way. 

Thanks.
