### ISSUE TITLE
Styling of inline code references

### ISSUE THREAD

**Issue by Bouke** [microsoft/sample-app-aoai-chatGPT#1104]
**Describe the bug**
Inline
```
codeblocks
```
are not 
```
rendered
```
on the
```
same line
```
.

**To Reproduce**
1. Trigger inline code blocks

**Expected behavior**
It should `render` inline `codeblocks` on the `same line`.

**Screenshots**
![image](https://github.com/user-attachments/assets/ba4a6f89-841b-468e-883c-69b289f5f88f)

**Configuration: Please provide the following**
N/A

**Logs**
N/A

**Additional context**
N/A

**Comment by Bouke** [comment]
I have added the following custom styles, which seem to work pretty ok:
```css
p > div {
	display: inline;
	line-height: inherit !important;
	margin: 0 !important;
	padding: 2px 4px !important;
}
```

![image](https://github.com/user-attachments/assets/7ea0b353-eb81-44c9-9ca9-14f2f6544012)
